[package]
name = "shellrs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dirs = "5.0.1"
home = "0.5.5"
hostname = "0.3.1"
users = "0.11.0"
